# Implementing Dirac...

In [19]:
import numpy as np

In [20]:
l = var('lambda_')
w = var('omega_')
t = var('t')
k = var('k')
E = var('E')
m = var('m')
p = var('p')
assume(l > 0)
assume(w > 0)
assume(t, l, k, w, m, 'real')
assume(t > 0)
assume(m > 0)
assume(l, w, k, m, 'constant')


## Looking at Pauli matrices

In [21]:
one = matrix([[1,0],[0,1]])
zero = matrix([[0,0], [0,0]])
p1 = matrix([[0,1],[1,0]])
p2 = matrix([[0,-1j],[1j,0]])
p3 = matrix([[1,0],[0,-1]])

In [22]:
def pauli(i):
    d = {1: p1, 2: p2, 3: p3}
    return d[i]
show(pauli(2))

[  0.000000000000000 -1.00000000000000*I]
[ 1.00000000000000*I   0.000000000000000]

In [23]:
def compose(a,b,c,d):
    # a b
    # c d
    return matrix(
        np.vstack([
            np.hstack([a,b]),
            np.hstack([c,d])
    ]))
show(compose(one, p1, p2, p3))

[   1.0    0.0    0.0    1.0]
[   0.0    1.0    1.0    0.0]
[   0.0 -1.0*I    1.0    0.0]
[ 1.0*I    0.0    0.0   -1.0]

In [24]:
g0 = compose(one, zero,
             zero, -one)
show(g0)

[ 1  0  0  0]
[ 0  1  0  0]
[ 0  0 -1  0]
[ 0  0  0 -1]

In [25]:
def gamma(i):
    if i == 0:
        return compose(one, zero, zero, -one)
    else:
        return compose(zero, pauli(i), -pauli(i), zero)
show(gamma(0))
show(gamma(1))
show(gamma(2))
show(gamma(3))

[ 1  0  0  0]
[ 0  1  0  0]
[ 0  0 -1  0]
[ 0  0  0 -1]

[ 0  0  0  1]
[ 0  0  1  0]
[ 0 -1  0  0]
[-1  0  0  0]

[   0.0    0.0    0.0 -1.0*I]
[   0.0    0.0  1.0*I    0.0]
[   0.0  1.0*I    0.0    0.0]
[-1.0*I    0.0    0.0    0.0]

[ 0  0  1  0]
[ 0  0  0 -1]
[-1  0  0  0]
[ 0  1  0  0]

In [26]:
def anticom(a,b):
    return a*b + b*a

In [27]:
rows = [[anticom(gamma(i), gamma(j)) for i in range(4)] for j in range(4)]
show(table(rows))

[2 0 0 0]
[0 2 0 0]
[0 0 2 0]
[0 0 0 2]                                   [0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]                                   [0.0 0.0 0.0 0.0]
[0.0 0.0 0.0 0.0]
[0.0 0.0 0.0 0.0]
[0.0 0.0 0.0 0.0]                   [0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
  [0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]                                   [-2  0  0  0]
[ 0 -2  0  0]
[ 0  0 -2  0]
[ 0  0  0 -2]                   [0.0 0.0 0.0 0.0]
[0.0 0.0 0.0 0.0]
[0.0 0.0 0.0 0.0]
[0.0 0.0 0.0 0.0]                   [0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
  [0.0 0.0 0.0 0.0]
[0.0 0.0 0.0 0.0]
[0.0 0.0 0.0 0.0]
[0.0 0.0 0.0 0.0]   [0.0 0.0 0.0 0.0]
[0.0 0.0 0.0 0.0]
[0.0 0.0 0.0 0.0]
[0.0 0.0 0.0 0.0]   [-2.0  0.0  0.0  0.0]
[ 0.0 -2.0  0.0  0.0]
[ 0.0  0.0 -2.0  0.0]
[ 0.0  0.0  0.0 -2.0]   [0.0 0.0 0.0 0.0]
[0.0 0.0 0.0 0.0]
[0.0 0.0 0.0 0.0]
[0.0 0.0 0.0 0.0]
  [0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]                                   [0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]                                   [0.0 0.0 0.0 0.0]
[0.0 0.0 0.0 0.0]
[0.0 0.0 0.0 0.0]
[0.0 0.0 0.0 0.0]                   [-2  0  0  0]
[ 0 -2  0  0]
[ 0  0 -2  0]
[ 0  0  0 -2]

In [28]:
# Check for a random 4-vector
r = vector([4, 7, 0, 2])
r

(4, 7, 0, 2)

In [29]:
z = sum(r[i] * gamma(i) for i in range(4))
z*z

[-37.0   0.0   0.0   0.0]
[  0.0 -37.0   0.0   0.0]
[  0.0   0.0 -37.0   0.0]
[  0.0   0.0   0.0 -37.0]

In [30]:
show(z)

[ 4.0  0.0  2.0  7.0]
[ 0.0  4.0  7.0 -2.0]
[-2.0 -7.0 -4.0  0.0]
[-7.0  2.0  0.0 -4.0]

## Defining a 4-spinor wave function
This is intended to be a solution to the Dirac equation.

In [31]:
t = var('t')
x,y,z = var("x,y,z")
r = vector([x,y,z])

def generate_dirac_psi(p, E, m):
    # Generate a 4-spinor state for a particle of momentum p, total energy E, mass m.
    # For this to satisfy the Dirac Equation, we requre E^2 = p^2 + m^2
    assert (E^2 == p.dot_product(p) + m^2)
    
    U = sqrt((E+m) / (2*E)) * vector ([1, 0, p[2]/(E+m), (p[0] + i * p[1])/(E+m)])

    return U * exp(i*(p.dot_product(r) - E*t))

In [32]:
# Generate a specific wave function to test
dirac_psi = generate_dirac_psi(p=vector([0,3,0]), E=5, m=4)
show(dirac_psi)

(3*sqrt(1/10)*e^(-5*I*t + 3*I*y), 0, 0, I*sqrt(1/10)*e^(-5*I*t + 3*I*y))

In [33]:
# Define the Dirac differentrial operator applied to the given wave function
def dirac_operator(psi, m):
    X = vector([t,r[0], r[1], r[2]])
    dirac = sum(gamma(q) * diff(psi, X[q]) for q in range(4))*i - m * psi
    return dirac

In [34]:

dirac = dirac_operator(dirac_psi, m=4)

In [35]:
show(dirac)

(0, 0, 0, 0)

In [36]:
if dirac == vector([0,0,0,0]):
    print("Looks like Dirac was right!")
else:
    print("Dirac was wrong (can't possibly be me!)")

Looks like Dirac was right!
